### ISSUE TITLE
Request package:  Trelby 2.2

### ISSUE THREAD

**Issue by carlos444** [coslyk/debianopt-repo#12]
### Package name
 Trelby 2.2

### Homepage
https://www.trelby.org/download/

### Description
The free, multiplatform, feature-rich screenwriting program!

depend package python-wxgtk2.8 that debian 10 not meet.

**Comment by coslyk** [comment]
Added in https://github.com/coslyk/debianopt-repo/commit/f8a0f7925dfe7596d5ede79fe1414d1eadb8eba0.
