### ISSUE TITLE
Request package: dde-file-manager

### ISSUE THREAD

**Issue by GoogleBeEvil** [coslyk/debianopt-repo#17]
### Package name
dde-file-manager

### Homepage
https://github.com/linuxdeepin/dde-file-manager

### Description
File manager for deepin desktop environment.

**Comment by coslyk** [comment]
This package cannot be added, because it has some 3rd-party dependencies that do not exist in the official repository:
```
dde-dock-dev
deepin-anything-dev
deepin-anything-server-dev
```
