### ISSUE TITLE
Request package: work_crawler

### ISSUE THREAD

**Issue by 2moe** [coslyk/debianopt-repo#18]
### Package name
work_crawler

### Homepage
[kanasimi/work_crawler](https://github.com/kanasimi/work_crawler)

### Description
Comics and novels download tool.
漫畫下載工具，該程式基於electron，打包起來很方便的。
直接用electron跑app.asar就可以了。

**Comment by coslyk** [comment]
源代码里面没有License文件，未知开源许可类型，因此无法添加到源里面 : (

**Comment by 2moe** [comment]
![Snipaste_2020-07-16_07-35-55.png](https://i.loli.net/2020/07/16/SeTgL96YbVAf8GN.png)  
"license" : "BSD-3-Clause"

**Comment by coslyk** [comment]
这个不算数的，必须要附一份License文件才有效，详见：https://opensource.stackexchange.com/a/7685
