### ISSUE TITLE
Discussion: error when I executed "apt update"

### ISSUE THREAD

**Issue by YaoLaiGang** [coslyk/debianopt-repo#19]
E: 无法下载 https://bintray.proxy.ustclug.org/debianopt/debianopt/dists/buster/main/binary-amd64/Packages.bz2  文件尺寸不符(11344 != 11345)。您使用的镜像正在同步中？ [IP: 103.121.209.188 443]
   Hashes of expected file:
    - Filesize:11345 [weak]
    - SHA256:4444cc5cba2327b9b7e075ec26dfc19c566cd48b6378177c43eed8aebaca0146
    - SHA1:dfe8286444fcea22c6de56b1704c5e61c953f981 [weak]
    - MD5Sum:720ad18017708a10f1920abfb519fc11 [weak]
   Release file created at: Wed, 15 Jul 2020 14:45:18 +0000
E: 部分索引文件下载失败。如果忽略它们，那将转而使用旧的索引文件。

**Comment by coslyk** [comment]
Should be fixed now.

**Comment by YaoLaiGang** [comment]
No problem now, thanks
