### ISSUE TITLE
Package broken: Listen1

### ISSUE THREAD

**Issue by 2moe** [coslyk/debianopt-repo#20]
### Package name
(Which package is broken?)
Listen1
### OS version
(Debian 10? Raspbian? Deepin? Or other Debian flavors?)
debian buster & debian sid & ubuntu focal 20.04
### Architecture
(amd64 / i386 / armhf / arm64 / mips64el?)
amd64&arm64
### Broken reason
(Dependencies broken? Errors during installation? Programm cannot start? Others?)
electron
### Error Log
![Capture__2020-08-27-23-01-02.png](https://i.loli.net/2020/08/27/ZgBpiEO8V7jaoSJ.png)

**Comment by 2moe** [comment]
旧版不存在此问题，这个问题是在最新版中出现的

**Comment by coslyk** [comment]
应当是上游代码的问题，我反馈到 https://github.com/listen1/listen1_desktop/issues/264 了。

和main.js没关系，源代码里面submodule地址有问题导致代码下载不全。

**Comment by coslyk** [comment]
Temporarily fixed in https://github.com/coslyk/debianopt-repo/commit/177a4cde16d65af0bf617bc16b3e35a89d29c038.
