### ISSUE TITLE
Request package: cherrytree 0.39.2

### ISSUE THREAD

**Issue by carlos444** [coslyk/debianopt-repo#5]
### Package name
cherrytree 0.39.2

### Homepage
https://www.giuspen.com/cherrytree/#downl

### Description
需要debian9的python-gtksourceview2

**Comment by coslyk** [comment]
Could you please open seperate issues for each package? (To make the status tracking more convenience)

 * cherrytree: planned
 * softmaker freeoffice: **This is not opensource so will not be planned**
 * freechat: planned
 * simplesok: planned
 * xnviewmp: **This is not opensource so will not be planned**
 * textadept: planned
 * menulibre: **already exists in official Debian repo**

**Comment by coslyk** [comment]
Since we only use dependencies from Debian's official repository (See the [packaging rules](https://github.com/coslyk/debianopt-repo/wiki/Packaging-rules)), this package cannot be added. Sorry : (
